config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'  #root :to => "Controller#action"

  get 'tasks/index'

  resources :tasks

  resources :articles do
    resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :task, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "myapp", password: "myapp", except: [:index, :show]

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "myapp", password: "myapp", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:name, :body)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @task = Task.new
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      render 'new'
    end 
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    
    if @task.update(task_params)
      redirect_to @task, :notice => "Success!"
    else
      render 'edit'
    end    
  end

  def destroy
    Task.destroy params[:id]
    redirect_to :back, :notice => "Task has been deleted."
  end

  private
  def task_params
    params.require(:task).permit(:task, :due)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
<% if @article.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@article.errors.count, "error") %> prohibited
    this article from being saved:</h2>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :text %><br>
  <%= f.text_area :text %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back to All Articles', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<%= link_to 'Create new article', new_article_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>

  <% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.text %></td>
    <td><%= link_to 'Show', article_path(article) %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
</table>

<p><%= link_to "Back to Home Page", root_path %></p>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back to All Articles', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render "comments/form" %>

<%= link_to 'Back', articles_path %>
| <%= link_to 'Edit', edit_article_path(@article) %>

app/views/comments/_comment.html.erb
<p>
  <strong>Name:</strong>
  <%= comment.name %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Delete Comment', [comment.article, comment],
  method: :delete,
  data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :body %><br>
  <%= f.text_area :body %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
<% if @task.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@task.errors.count, "error") %> prohibited
    this task from being saved:</h2>
    <ul>
      <% @task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
</div>
<% end %>
<div>
  <p>
  <%= f.label :task %>
  </p>
  <p>
  <%= f.text_field :task %>
  </p>

  <p>
  <%= f.label :due %> (YYYY-MM-DD)
  </p>
  <p>
  <%= f.text_field :due %>  
  </p>
  <p>
  <%= f.submit %>
  </p>
</div>  
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render "form" %>

app/views/tasks/index.html.erb
<% flash.each do |name, message| %>

  <%= content_tag :div, message, :id => "flash_#{name}" %>

<% end %>

<h1>Listing all Tasks</h1>

<ul>
  <% for task in @tasks %>
<!--
    <table>
      <tr>
        <td style="width:500px"><li id="task_<%= task.id %>"><%= task.task %></li></td>
        <td style="width:150px"><strong>Due:</strong> <%= task.due %></td>
        <td><%= link_to "Edit", edit_task_path(task) %></td>
        <td><%= link_to "Delete", task, :method => "Delete" %></td>
      </tr>
    </table>
-->
    <li id="task_<%= task.id %>">
      <%= task.task %>
      | <%= task.due %>
      | <%= link_to "Edit", edit_task_path(task) %>
      | <%= link_to "Delete", task, :method => "Delete" %>
    </li>    

  <% end %>
</ul>

<p><%= link_to "Create New Task", new_task_path %></p>
<p><%= link_to "Back to Home Page", root_path %></p>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back to All Tasks', tasks_path %>

app/views/tasks/show.html.erb
<% flash.each do |name, message| %>
  <!-- <div id="flash_<%= name %>">
    <%= message %>
  </div> -->    <!-- Both forms are equivalent -->

  <%= content_tag :div, message, :id => "flash_#{name}" %>

<% end %>

<p>
  <strong>Task:</strong>
  <%= @task.task %>
</p>
<p>
  <strong>Due:</strong>
  <%= @task.due %>
</p>

<%= link_to 'Back to Tasks', tasks_path %>

app/views/welcome/index.html.erb
<div align="middle"><%= image_tag "welcome-sign-1.jpg" %></div>

<div id = "links">
<p class = "welcome"><%= link_to 'My Blog', controller: 'articles' %></p>

<p class = "welcome"><%= link_to 'Tasks', controller: 'tasks' %></p>
</div>